spring:
  application:
    name: order-service-graphql
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  graphql:
    path: /graphql

server:
  port: 8082
