services:
  # Servicio de MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Servicio de la aplicación Node.js
  app:
    build: .
    container_name: nodejs_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/usuarios
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge